name: Check Ubuntu 16.04

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'            # We don't want this to run on release
  pull_request:

jobs:
  build-ubuntu16:
    name: Ubuntu 16.04
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        run: |
          BOOST_ROOT=
          sudo apt install -y libboost-all-dev
          build_folder="build/release"
          krb_ver=${GITHUB_SHA::7}
          krb_ver_folder=$(echo $krb_ver | sed 's/\.//g')
          release_name=Karbo-cli-ubuntu16.04-"$krb_ver"
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -D CMAKE_BUILD_TYPE=Release ../..
          make
          mkdir -p "$release_name/$krb_ver_folder"
          exeFiles=()
          for f in src/*; do [[ -x $f && -f $f ]] && exeFiles+=( "$f" ); done
          cp "${exeFiles[@]}" "$release_name/$krb_ver_folder"
          cd "$release_name"
          tar -czf "$release_name".tar.gz "$krb_ver_folder"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name/$release_name.tar.gz"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=krb_ver::${krb_ver}"

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.build.outputs.release_name }}
          path: ${{ steps.build.outputs.asset_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
